// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Services.PhoneAPI.DbContexts;

#nullable disable

namespace Shop.Services.PhoneAPI.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20220608151233_addPhoneInDb")]
    partial class addPhoneInDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shop.Services.PhoneAPI.Models.Goods", b =>
                {
                    b.Property<int>("GoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GoodId");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            GoodId = 1,
                            CategoryName = "Phone",
                            Description = "Apple iPhone 11 поражает возможностями.",
                            ImageUrl = "https://storage.yandexcloud.net/foxstoragearbfirst/Phones/11.png",
                            Name = "Iphone 11",
                            Price = 45000m
                        },
                        new
                        {
                            GoodId = 2,
                            CategoryName = "Phone",
                            Description = "Apple iPhone 12 поражает возможностями. Высокопроизводительный процессор от Apple A14 Bionic для iPhone.<br/>Обновленная система двух камер 12 Мп: сверхширокоугольная и широкоугольная.",
                            ImageUrl = "https://storage.yandexcloud.net/foxstoragearbfirst/Phones/12.png",
                            Name = "Iphone 12",
                            Price = 50000m
                        },
                        new
                        {
                            GoodId = 3,
                            CategoryName = "Phone",
                            Description = "Невероятно быстрый и энергоэффективный новый процессор A15 Bionic в Apple iPhone 13 512GB обеспечивает работу режима «Киноэффект», Фотографических стилей и других функций.<br/>Secure Enclave защищает персональные данные, включая Face ID и контакты.",
                            ImageUrl = "https://storage.yandexcloud.net/foxstoragearbfirst/Phones/13.png",
                            Name = "Iphone 13",
                            Price = 61000.99m
                        },
                        new
                        {
                            GoodId = 4,
                            CategoryName = "Phone",
                            Description = "Безграничный экран",
                            ImageUrl = "https://storage.yandexcloud.net/foxstoragearbfirst/Phones/14.png",
                            Name = "Iphone 14",
                            Price = 99000.05m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
